import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'ta' | 'kn' | 'ml';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.shop': 'Shop',
    'nav.cart': 'Cart',
    'nav.profile': 'Profile',
    'nav.language': 'Language',
    
    // Common
    'common.addToCart': 'Add to Cart',
    'common.quantity': 'Quantity',
    'common.price': 'Price',
    'common.total': 'Total',
    'common.subtotal': 'Subtotal',
    'common.deliveryFee': 'Delivery Fee',
    'common.free': 'FREE',
    'common.checkout': 'Checkout',
    'common.continue': 'Continue',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.all': 'All',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    
    // Delivery Options
    'delivery.delivery': 'Home Delivery',
    'delivery.walkIn': 'Walk-in Pickup',
    'delivery.scheduled': 'Scheduled Order',
    'delivery.selectOption': 'Select Delivery Option',
    'delivery.deliveryDesc': 'Get your order delivered to your doorstep',
    'delivery.walkInDesc': 'Pick up your order from the store',
    'delivery.scheduledDesc': 'Schedule your order for later pickup or delivery',
    'delivery.selectTime': 'Select Time',
    'delivery.selectDate': 'Select Date',
    
    // Recipe Packages
    'recipe.packages': 'Recipe Packages',
    'recipe.suggested': 'Suggested Dishes',
    'recipe.ingredients': 'Ingredients',
    'recipe.discount': '10% OFF',
    'recipe.chickenBiryani': 'Chicken Biryani',
    'recipe.dalRice': 'Dal Rice',
    'recipe.vegetableCurry': 'Vegetable Curry',
    'recipe.eggFriedRice': 'Egg Fried Rice',
    'recipe.paneerButterMasala': 'Paneer Butter Masala',
    'recipe.addPackage': 'Add Package to Cart',
    'recipe.serves': 'Serves',
    'recipe.persons': 'persons',
    'recipe.chickenBiryaniDesc': 'Aromatic basmati rice with tender chicken and fragrant spices',
    'recipe.dalRiceDesc': 'Comforting dal with steamed rice - a perfect meal',
    'recipe.vegetableCurryDesc': 'Mixed vegetables in a rich, flavorful curry',
    'recipe.eggFriedRiceDesc': 'Quick and delicious egg fried rice with vegetables',
    'recipe.paneerButterMasalaDesc': 'Creamy paneer in rich tomato and butter gravy',
    'recipe.chicken1kg': 'Fresh Chicken 1kg',
    'recipe.basmatiRice': 'Basmati Rice',
    'recipe.sonaRice': 'Sona Masoori Rice',
    'recipe.toorDal': 'Toor Dal',
    'recipe.turmeric': 'Turmeric Powder',
    'recipe.redChili': 'Red Chili Powder',
    'recipe.onions': 'Onions',
    'recipe.tomatoes': 'Tomatoes',
    'recipe.potatoes': 'Potatoes',
    'recipe.coconutOil': 'Coconut Oil',
    'recipe.butter': 'Butter',
    
    // Categories
    'category.riceGrains': 'Rice & Grains',
    'category.pulses': 'Pulses',
    'category.cookingOil': 'Cooking Oil',
    'category.dairy': 'Dairy',
    'category.vegetables': 'Vegetables',
    'category.bakery': 'Bakery',
    'category.spices': 'Spices',
    'category.beverages': 'Beverages',
    'category.snacks': 'Snacks',
    'category.chicken': 'Chicken',
    'category.mutton': 'Mutton',
    'category.fish': 'Fish',
    'category.beef': 'Beef',
    'category.pork': 'Pork',
    'category.personalCare': 'Personal Care',
    'category.household': 'Household',
    
    // Store Types
    'store.kirana': 'Kirana Store',
    'store.supermarket': 'Supermarket',
    'store.meat': 'Meat Store',
    'store.local': 'Local Stores',
    'store.nearYou': 'Near You',
    'store.open': 'stores open',
    
    // Popular Products
    'products.popular': 'Popular Products',
    'products.featured': 'Featured Products',
    'products.recommended': 'Recommended for You',
    
    // Checkout
    'checkout.title': 'Checkout',
    'checkout.deliveryAddress': 'Delivery Address',
    'checkout.paymentMethod': 'Payment Method',
    'checkout.orderSummary': 'Order Summary',
    'checkout.placeOrder': 'Place Order',
    'checkout.processing': 'Processing Payment...',
    'checkout.success': 'Order Placed Successfully!',
    'checkout.failed': 'Payment Failed',
    
    // Cart
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.continueShopping': 'Continue Shopping',
    'cart.proceedToCheckout': 'Proceed to Checkout',
    'cart.removeItem': 'Remove Item',
    'cart.updateQuantity': 'Update Quantity',
    
    // Time
    'time.minutes': 'min',
    'time.hours': 'hr',
    'time.days': 'days',
    'time.weeks': 'weeks',
    'time.months': 'months',
    'time.years': 'years',
    
    // Home Page
    'home.title': 'From Your Street, To Your Seat',
    'home.subtitle': 'Connect with your local stores in Bangalore. Get fresh groceries, daily essentials, and more delivered to your doorstep.',
    'home.startShopping': 'Start Shopping',
    'home.startShoppingNow': 'Start Shopping Now',
    'home.joinAsVendor': 'Join as Store Owner',
    'home.joinAsDelivery': 'Join as Delivery Partner',
    'home.whyChoose': 'Why Choose Kiro?',
    'home.fastDelivery': 'Lightning fast delivery from nearby local stores',
    'home.freshProducts': 'Fresh products delivered daily',
    'home.supportLocal': 'Help your neighborhood local stores grow',
    'home.copyright': '© 2025 Kiro. All rights reserved.',
    'home.features': 'Features',
    'home.howItWorks': 'How it Works',
    'home.contact': 'Contact',
    'home.forStores': 'For Stores',
    'home.forDelivery': 'For Delivery',
    'home.readyToConnect': 'Ready to Connect with Local Stores?',
    'home.joinThousands': 'Join thousands of customers who are already enjoying the convenience of local store delivery.',
    'home.localStores': 'Local Stores',
    'home.happyCustomers': 'Happy Customers',
    'home.avgDelivery': 'Avg Delivery',
    'home.rating': 'Rating',
    'home.localKiranaStores': 'Local Kirana Stores',
    'home.localStoresDesc': 'Connect with nearby kirana stores and small shops',
    'home.realTimeNotifications': 'Real-time Notifications',
    'home.notificationsDesc': 'Store owners get instant order notifications',
    'home.fastDeliveryTitle': 'Fast Delivery',
    'home.fastDeliveryDesc': 'Quick delivery from your neighborhood stores',
    'home.browseStores': 'Browse Local Stores',
    'home.browseStoresDesc': 'Discover nearby kirana stores and small shops in your area',
    'home.placeOrder': 'Place Your Order',
    'home.placeOrderDesc': 'Add items to cart and place your order with real-time notifications',
    'home.getDelivered': 'Get Delivered',
    'home.getDeliveredDesc': 'Receive your order quickly with live tracking and updates',
    'home.product': 'Product',
    'home.forStoresTitle': 'For Stores',
    'home.vendorDashboard': 'Vendor Dashboard',
    'home.howToJoin': 'How to Join',
    'home.support': 'Support',
    'home.helpCenter': 'Help Center',
    'home.privacy': 'Privacy',
    'home.connectingStores': 'Connecting local stores with customers for a better shopping experience.',
    
    // Login/Signup
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.phone': 'Phone Number',
    'auth.name': 'Full Name',
    'auth.storeName': 'Store Name',
    'auth.address': 'Address',
    'auth.rememberMe': 'Remember me',
    'auth.forgotPassword': 'Forgot password?',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.customerLogin': 'Customer Login',
    'auth.vendorLogin': 'Store Owner Login',
    'auth.deliveryLogin': 'Delivery Partner Login',
    'auth.customerSignup': 'Customer Signup',
    'auth.vendorSignup': 'Store Owner Signup',
    'auth.deliverySignup': 'Delivery Partner Signup',
    
    // Dashboard
    'dashboard.orders': 'Orders',
    'dashboard.revenue': 'Revenue',
    'dashboard.customers': 'Customers',
    'dashboard.products': 'Products',
    'dashboard.pendingOrders': 'Pending Orders',
    'dashboard.acceptedOrders': 'Accepted Orders',
    'dashboard.deliveredOrders': 'Delivered Orders',
    'dashboard.totalRevenue': 'Total Revenue',
    'dashboard.todayRevenue': "Today's Revenue",
    'dashboard.newCustomers': 'New Customers',
    'dashboard.totalProducts': 'Total Products',
    'dashboard.accept': 'Accept',
    'dashboard.reject': 'Reject',
    'dashboard.markDelivered': 'Mark as Delivered',
    'dashboard.orderDetails': 'Order Details',
    'dashboard.customerName': 'Customer Name',
    'dashboard.orderTotal': 'Order Total',
    'dashboard.paymentStatus': 'Payment Status',
    'dashboard.deliveryAddress': 'Delivery Address',
    'dashboard.orderTime': 'Order Time',
    'dashboard.notes': 'Notes',
    
    // Delivery
    'delivery.availableOrders': 'Available Orders',
    'delivery.myOrders': 'My Orders',
    'delivery.pickup': 'Pickup',
    'delivery.deliver': 'Deliver',
    'delivery.complete': 'Complete',
    'delivery.earnings': 'Earnings',
    'delivery.totalEarnings': 'Total Earnings',
    'delivery.todayEarnings': "Today's Earnings",
    'delivery.completedDeliveries': 'Completed Deliveries',
    'delivery.rating': 'Rating',
    
    // Notifications
    'notification.newOrder': 'New Order Received',
    'notification.orderAccepted': 'Order Accepted',
    'notification.orderDelivered': 'Order Delivered',
    'notification.specialOffer': 'Special Offer',
    'notification.discountAvailable': 'Discount Available',
    'notification.hotSpot': 'Hot Delivery Spot',
    'notification.bestSeller': 'Best Selling Product',
    'notification.lowStock': 'Low Stock Alert',
    'notification.paymentReceived': 'Payment Received',
    
    // Common Actions
    'action.view': 'View',
    'action.edit': 'Edit',
    'action.delete': 'Delete',
    'action.save': 'Save',
    'action.cancel': 'Cancel',
    'action.confirm': 'Confirm',
    'action.submit': 'Submit',
    'action.reset': 'Reset',
    'action.refresh': 'Refresh',
    'action.loading': 'Loading...',
    'action.processing': 'Processing...',
    'action.success': 'Success',
    'action.error': 'Error',
    'action.warning': 'Warning',
    'action.info': 'Info',
  },
  
  hi: {
    // Navigation
    'nav.home': 'होम',
    'nav.shop': 'शॉप',
    'nav.cart': 'कार्ट',
    'nav.profile': 'प्रोफाइल',
    'nav.language': 'भाषा',
    
    // Common
    'common.addToCart': 'कार्ट में जोड़ें',
    'common.quantity': 'मात्रा',
    'common.price': 'कीमत',
    'common.total': 'कुल',
    'common.subtotal': 'उप-योग',
    'common.deliveryFee': 'डिलीवरी शुल्क',
    'common.free': 'मुफ्त',
    'common.checkout': 'चेकआउट',
    'common.continue': 'जारी रखें',
    'common.cancel': 'रद्द करें',
    'common.save': 'सेव करें',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएं',
    'common.view': 'देखें',
    'common.close': 'बंद करें',
    'common.back': 'वापस',
    'common.next': 'अगला',
    'common.previous': 'पिछला',
    'common.search': 'खोजें',
    'common.filter': 'फिल्टर',
    'common.sort': 'सॉर्ट',
    'common.all': 'सभी',
    'common.yes': 'हां',
    'common.no': 'नहीं',
    'common.ok': 'ठीक है',
    
    // Delivery Options
    'delivery.delivery': 'होम डिलीवरी',
    'delivery.walkIn': 'वॉक-इन पिकअप',
    'delivery.scheduled': 'शेड्यूल्ड ऑर्डर',
    'delivery.selectOption': 'डिलीवरी विकल्प चुनें',
    'delivery.deliveryDesc': 'अपना ऑर्डर घर पर मंगवाएं',
    'delivery.walkInDesc': 'स्टोर से अपना ऑर्डर उठाएं',
    'delivery.scheduledDesc': 'बाद में पिकअप या डिलीवरी के लिए अपना ऑर्डर शेड्यूल करें',
    'delivery.selectTime': 'समय चुनें',
    'delivery.selectDate': 'तारीख चुनें',
    
    // Recipe Packages
    'recipe.packages': 'रेसिपी पैकेज',
    'recipe.suggested': 'सुझाए गए व्यंजन',
    'recipe.ingredients': 'सामग्री',
    'recipe.discount': '10% छूट',
    'recipe.chickenBiryani': 'चिकन बिरयानी',
    'recipe.dalRice': 'दाल चावल',
    'recipe.vegetableCurry': 'सब्जी करी',
    'recipe.eggFriedRice': 'अंडा फ्राइड राइस',
    'recipe.paneerButterMasala': 'पनीर बटर मसाला',
    'recipe.addPackage': 'पैकेज कार्ट में जोड़ें',
    'recipe.serves': 'सर्विंग्स',
    'recipe.persons': 'लोग',
    
    // Categories
    'category.riceGrains': 'चावल और अनाज',
    'category.pulses': 'दालें',
    'category.cookingOil': 'खाना पकाने का तेल',
    'category.dairy': 'डेयरी',
    'category.vegetables': 'सब्जियां',
    'category.bakery': 'बेकरी',
    'category.spices': 'मसाले',
    'category.beverages': 'पेय',
    'category.snacks': 'नाश्ता',
    'category.chicken': 'चिकन',
    'category.mutton': 'मटन',
    'category.fish': 'मछली',
    'category.beef': 'बीफ',
    'category.pork': 'पोर्क',
    'category.personalCare': 'व्यक्तिगत देखभाल',
    'category.household': 'घरेलू सामान',
    
    // Store Types
    'store.kirana': 'किराना स्टोर',
    'store.supermarket': 'सुपरमार्केट',
    'store.meat': 'मीट स्टोर',
    'store.local': 'स्थानीय स्टोर',
    'store.nearYou': 'आपके पास',
    'store.open': 'स्टोर खुले',
    
    // Popular Products
    'products.popular': 'लोकप्रिय उत्पाद',
    'products.featured': 'विशेष उत्पाद',
    'products.recommended': 'आपके लिए सुझाए गए',
    
    // Checkout
    'checkout.title': 'चेकआउट',
    'checkout.deliveryAddress': 'डिलीवरी पता',
    'checkout.paymentMethod': 'भुगतान विधि',
    'checkout.orderSummary': 'ऑर्डर सारांश',
    'checkout.placeOrder': 'ऑर्डर दें',
    'checkout.processing': 'भुगतान प्रोसेसिंग...',
    'checkout.success': 'ऑर्डर सफलतापूर्वक दिया गया!',
    'checkout.failed': 'भुगतान असफल',
    
    // Cart
    'cart.title': 'शॉपिंग कार्ट',
    'cart.empty': 'आपका कार्ट खाली है',
    'cart.continueShopping': 'खरीदारी जारी रखें',
    'cart.proceedToCheckout': 'चेकआउट पर जाएं',
    'cart.removeItem': 'आइटम हटाएं',
    'cart.updateQuantity': 'मात्रा अपडेट करें',
    
    // Time
    'time.minutes': 'मिनट',
    'time.hours': 'घंटे',
    'time.days': 'दिन',
    'time.weeks': 'सप्ताह',
    'time.months': 'महीने',
    'time.years': 'साल',
    
    // Home Page
    'home.title': 'From Your Street, To Your Seat',
    'home.subtitle': 'बैंगलोर में अपने स्थानीय स्टोर से जुड़ें। ताजी सब्जियां, दैनिक जरूरतों का सामान और बहुत कुछ अपने दरवाजे पर मंगवाएं।',
    'home.startShopping': 'खरीदारी शुरू करें',
    'home.startShoppingNow': 'अभी खरीदारी शुरू करें',
    'home.joinAsVendor': 'स्टोर मालिक के रूप में जुड़ें',
    'home.joinAsDelivery': 'डिलीवरी पार्टनर के रूप में जुड़ें',
    'home.whyChoose': 'किरो क्यों चुनें?',
    'home.fastDelivery': 'पास के स्थानीय स्टोर से तेज डिलीवरी',
    'home.freshProducts': 'ताजे उत्पाद रोजाना डिलीवर',
    'home.supportLocal': 'अपने पड़ोस के स्थानीय स्टोर को बढ़ने में मदद करें',
    'home.copyright': '© 2025 किरो। सभी अधिकार सुरक्षित।',
    'home.features': 'फीचर्स',
    'home.howItWorks': 'यह कैसे काम करता है',
    'home.contact': 'संपर्क',
    'home.forStores': 'स्टोर के लिए',
    'home.forDelivery': 'डिलीवरी के लिए',
    'home.readyToConnect': 'स्थानीय स्टोर से जुड़ने के लिए तैयार?',
    'home.joinThousands': 'हजारों ग्राहकों के साथ जुड़ें जो पहले से ही स्थानीय स्टोर डिलीवरी की सुविधा का आनंद ले रहे हैं।',
    'home.localStores': 'स्थानीय स्टोर',
    'home.happyCustomers': 'खुश ग्राहक',
    'home.avgDelivery': 'औसत डिलीवरी',
    'home.rating': 'रेटिंग',
    'home.localKiranaStores': 'स्थानीय किराना स्टोर',
    'home.localStoresDesc': 'पास के किराना स्टोर और छोटी दुकानों से जुड़ें',
    'home.realTimeNotifications': 'रियल-टाइम नोटिफिकेशन',
    'home.notificationsDesc': 'स्टोर मालिकों को तुरंत ऑर्डर नोटिफिकेशन मिलते हैं',
    'home.fastDeliveryTitle': 'तेज डिलीवरी',
    'home.fastDeliveryDesc': 'आपके पड़ोस के स्टोर से तेज डिलीवरी',
    'home.browseStores': 'स्थानीय स्टोर ब्राउज़ करें',
    'home.browseStoresDesc': 'अपने क्षेत्र में पास के किराना स्टोर और छोटी दुकानों की खोज करें',
    'home.placeOrder': 'अपना ऑर्डर दें',
    'home.placeOrderDesc': 'आइटम को कार्ट में जोड़ें और रियल-टाइम नोटिफिकेशन के साथ अपना ऑर्डर दें',
    'home.getDelivered': 'डिलीवर करवाएं',
    'home.getDeliveredDesc': 'लाइव ट्रैकिंग और अपडेट के साथ अपना ऑर्डर जल्दी प्राप्त करें',
    'home.product': 'उत्पाद',
    'home.forStoresTitle': 'स्टोर के लिए',
    'home.vendorDashboard': 'वेंडर डैशबोर्ड',
    'home.howToJoin': 'कैसे जुड़ें',
    'home.support': 'सहायता',
    'home.helpCenter': 'हेल्प सेंटर',
    'home.privacy': 'गोपनीयता',
    'home.connectingStores': 'बेहतर खरीदारी अनुभव के लिए स्थानीय स्टोर को ग्राहकों से जोड़ना।',
    
    // Login/Signup
    'auth.login': 'लॉगिन',
    'auth.signup': 'साइन अप',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.confirmPassword': 'पासवर्ड की पुष्टि करें',
    'auth.phone': 'फोन नंबर',
    'auth.name': 'पूरा नाम',
    'auth.storeName': 'स्टोर का नाम',
    'auth.address': 'पता',
    'auth.rememberMe': 'मुझे याद रखें',
    'auth.forgotPassword': 'पासवर्ड भूल गए?',
    'auth.dontHaveAccount': 'खाता नहीं है?',
    'auth.alreadyHaveAccount': 'पहले से खाता है?',
    'auth.customerLogin': 'ग्राहक लॉगिन',
    'auth.vendorLogin': 'स्टोर मालिक लॉगिन',
    'auth.deliveryLogin': 'डिलीवरी पार्टनर लॉगिन',
    'auth.customerSignup': 'ग्राहक साइन अप',
    'auth.vendorSignup': 'स्टोर मालिक साइन अप',
    'auth.deliverySignup': 'डिलीवरी पार्टनर साइन अप',
    
    // Dashboard
    'dashboard.orders': 'ऑर्डर',
    'dashboard.revenue': 'रेवेन्यू',
    'dashboard.customers': 'ग्राहक',
    'dashboard.products': 'उत्पाद',
    'dashboard.pendingOrders': 'लंबित ऑर्डर',
    'dashboard.acceptedOrders': 'स्वीकृत ऑर्डर',
    'dashboard.deliveredOrders': 'डिलीवर किए गए ऑर्डर',
    'dashboard.totalRevenue': 'कुल रेवेन्यू',
    'dashboard.todayRevenue': 'आज का रेवेन्यू',
    'dashboard.newCustomers': 'नए ग्राहक',
    'dashboard.totalProducts': 'कुल उत्पाद',
    'dashboard.accept': 'स्वीकार करें',
    'dashboard.reject': 'अस्वीकार करें',
    'dashboard.markDelivered': 'डिलीवर के रूप में चिह्नित करें',
    'dashboard.orderDetails': 'ऑर्डर विवरण',
    'dashboard.customerName': 'ग्राहक का नाम',
    'dashboard.orderTotal': 'ऑर्डर कुल',
    'dashboard.paymentStatus': 'भुगतान स्थिति',
    'dashboard.deliveryAddress': 'डिलीवरी पता',
    'dashboard.orderTime': 'ऑर्डर समय',
    'dashboard.notes': 'नोट्स',
    
    // Delivery
    'delivery.availableOrders': 'उपलब्ध ऑर्डर',
    'delivery.myOrders': 'मेरे ऑर्डर',
    'delivery.pickup': 'पिकअप',
    'delivery.deliver': 'डिलीवर',
    'delivery.complete': 'पूरा करें',
    'delivery.earnings': 'कमाई',
    'delivery.totalEarnings': 'कुल कमाई',
    'delivery.todayEarnings': 'आज की कमाई',
    'delivery.completedDeliveries': 'पूर्ण डिलीवरी',
    'delivery.rating': 'रेटिंग',
    
    // Notifications
    'notification.newOrder': 'नया ऑर्डर प्राप्त हुआ',
    'notification.orderAccepted': 'ऑर्डर स्वीकृत',
    'notification.orderDelivered': 'ऑर्डर डिलीवर',
    'notification.specialOffer': 'विशेष ऑफर',
    'notification.discountAvailable': 'छूट उपलब्ध',
    'notification.hotSpot': 'हॉट डिलीवरी स्पॉट',
    'notification.bestSeller': 'सबसे ज्यादा बिकने वाला उत्पाद',
    'notification.lowStock': 'कम स्टॉक चेतावनी',
    'notification.paymentReceived': 'भुगतान प्राप्त',
    
    // Common Actions
    'action.view': 'देखें',
    'action.edit': 'संपादित करें',
    'action.delete': 'हटाएं',
    'action.save': 'सेव करें',
    'action.cancel': 'रद्द करें',
    'action.confirm': 'पुष्टि करें',
    'action.submit': 'जमा करें',
    'action.reset': 'रीसेट करें',
    'action.refresh': 'रिफ्रेश करें',
    'action.loading': 'लोड हो रहा है...',
    'action.processing': 'प्रोसेसिंग...',
    'action.success': 'सफल',
    'action.error': 'त्रुटि',
    'action.warning': 'चेतावनी',
    'action.info': 'जानकारी',
  },
  
  ta: {
    // Navigation
    'nav.home': 'முகப்பு',
    'nav.shop': 'கடை',
    'nav.cart': 'கார்ட்',
    'nav.profile': 'சுயவிவரம்',
    'nav.language': 'மொழி',
    
    // Common
    'common.addToCart': 'கார்ட்டில் சேர்',
    'common.quantity': 'அளவு',
    'common.price': 'விலை',
    'common.total': 'மொத்தம்',
    'common.subtotal': 'துணை மொத்தம்',
    'common.deliveryFee': 'டெலிவரி கட்டணம்',
    'common.free': 'இலவசம்',
    'common.checkout': 'செக்அவுட்',
    'common.continue': 'தொடர',
    'common.cancel': 'ரத்து',
    'common.save': 'சேமி',
    'common.edit': 'திருத்து',
    'common.delete': 'நீக்கு',
    'common.view': 'பார்',
    'common.close': 'மூடு',
    'common.back': 'பின்',
    'common.next': 'அடுத்து',
    'common.previous': 'முந்தைய',
    'common.search': 'தேடு',
    'common.filter': 'வடிகட்டு',
    'common.sort': 'வரிசைப்படுத்து',
    'common.all': 'அனைத்தும்',
    'common.yes': 'ஆம்',
    'common.no': 'இல்லை',
    'common.ok': 'சரி',
    
    // Delivery Options
    'delivery.delivery': 'வீட்டு டெலிவரி',
    'delivery.walkIn': 'நடந்து வந்து எடுத்துச் செல்',
    'delivery.scheduled': 'திட்டமிடப்பட்ட ஆர்டர்',
    'delivery.selectOption': 'டெலிவரி விருப்பத்தைத் தேர்ந்தெடுக்கவும்',
    'delivery.deliveryDesc': 'உங்கள் ஆர்டரை வீட்டிற்கு டெலிவரி செய்யுங்கள்',
    'delivery.walkInDesc': 'கடையிலிருந்து உங்கள் ஆர்டரை எடுத்துச் செல்லுங்கள்',
    'delivery.scheduledDesc': 'பின்னர் எடுத்துச் செல்ல அல்லது டெலிவரிக்கு உங்கள் ஆர்டரை திட்டமிடுங்கள்',
    'delivery.selectTime': 'நேரத்தைத் தேர்ந்தெடுக்கவும்',
    'delivery.selectDate': 'தேதியைத் தேர்ந்தெடுக்கவும்',
    
    // Recipe Packages
    'recipe.packages': 'விரும்பிய பாக்கெட்கள்',
    'recipe.suggested': 'பரிந்துரைக்கப்பட்ட உணவுகள்',
    'recipe.ingredients': 'பொருட்கள்',
    'recipe.discount': '10% தள்ளுபடி',
    'recipe.chickenBiryani': 'சிக்கன் பிரியாணி',
    'recipe.dalRice': 'தால் சாதம்',
    'recipe.vegetableCurry': 'காய்கறி கறி',
    'recipe.eggFriedRice': 'முட்டை வறுத்த சாதம்',
    'recipe.paneerButterMasala': 'பன்னீர் பட்டர் மசாலா',
    'recipe.addPackage': 'கார்ட்டில் பாக்கெட் சேர்',
    'recipe.serves': 'பரிமாறுகிறது',
    'recipe.persons': 'பேர்',
    
    // Categories
    'category.riceGrains': 'அரிசி மற்றும் தானியங்கள்',
    'category.pulses': 'பருப்பு வகைகள்',
    'category.cookingOil': 'சமையல் எண்ணெய்',
    'category.dairy': 'பால் பொருட்கள்',
    'category.vegetables': 'காய்கறிகள்',
    'category.bakery': 'பேக்கரி',
    'category.spices': 'மசாலாப் பொருட்கள்',
    'category.beverages': 'பானங்கள்',
    'category.snacks': 'சிற்றுண்டி',
    'category.chicken': 'சிக்கன்',
    'category.mutton': 'ஆட்டிறைச்சி',
    'category.fish': 'மீன்',
    'category.beef': 'மாட்டிறைச்சி',
    'category.pork': 'பன்றி இறைச்சி',
    'category.personalCare': 'தனிப்பட்ட பராமரிப்பு',
    'category.household': 'வீட்டு சாமான்கள்',
    
    // Store Types
    'store.kirana': 'கிரானா கடை',
    'store.supermarket': 'சூப்பர் மார்க்கெட்',
    'store.meat': 'இறைச்சி கடை',
    'store.local': 'உள்ளூர் கடைகள்',
    'store.nearYou': 'உங்களுக்கு அருகில்',
    'store.open': 'கடைகள் திறந்திருக்கும்',
    
    // Popular Products
    'products.popular': 'பிரபலமான தயாரிப்புகள்',
    'products.featured': 'சிறப்பு தயாரிப்புகள்',
    'products.recommended': 'உங்களுக்கு பரிந்துரைக்கப்பட்டவை',
    
    // Checkout
    'checkout.title': 'செக்அவுட்',
    'checkout.deliveryAddress': 'டெலிவரி முகவரி',
    'checkout.paymentMethod': 'கட்டண முறை',
    'checkout.orderSummary': 'ஆர்டர் சுருக்கம்',
    'checkout.placeOrder': 'ஆர்டர் செய்',
    'checkout.processing': 'கட்டணம் செயலாக்கப்படுகிறது...',
    'checkout.success': 'ஆர்டர் வெற்றிகரமாக வைக்கப்பட்டது!',
    'checkout.failed': 'கட்டணம் தோல்வி',
    
    // Cart
    'cart.title': 'ஷாப்பிங் கார்ட்',
    'cart.empty': 'உங்கள் கார்ட் காலியாக உள்ளது',
    'cart.continueShopping': 'ஷாப்பிங் தொடர',
    'cart.proceedToCheckout': 'செக்அவுட்டுக்குச் செல்',
    'cart.removeItem': 'ஐடத்தை நீக்கு',
    'cart.updateQuantity': 'அளவை புதுப்பி',
    
    // Time
    'time.minutes': 'நிமிடங்கள்',
    'time.hours': 'மணிநேரம்',
    'time.days': 'நாட்கள்',
    'time.weeks': 'வாரங்கள்',
    'time.months': 'மாதங்கள்',
    'time.years': 'ஆண்டுகள்',
    
    // Home Page
    'home.title': 'From Your Street, To Your Seat',
    'home.subtitle': 'Connect with your local stores in Bangalore. Get fresh groceries, daily essentials, and more delivered to your doorstep.',
    'home.startShopping': 'ஷாப்பிங் தொடங்க',
    'home.startShoppingNow': 'இப்போது ஷாப்பிங் தொடங்க',
    'home.joinAsVendor': 'கடை உரிமையாளராக சேர',
    'home.joinAsDelivery': 'டெலிவரி பார்ட்னராக சேர',
    'home.whyChoose': 'ஏன் கிரோவை தேர்ந்தெடுக்க வேண்டும்?',
    'home.features': 'அம்சங்கள்',
    'home.howItWorks': 'இது எப்படி வேலை செய்கிறது',
    'home.contact': 'தொடர்பு',
    'home.localStores': 'உள்ளூர் கடைகள்',
    'home.happyCustomers': 'மகிழ்ச்சியான வாடிக்கையாளர்கள்',
    'home.avgDelivery': 'சராசரி டெலிவரி',
    'home.rating': 'மதிப்பீடு',
    'home.product': 'தயாரிப்பு',
    'home.forStoresTitle': 'கடைகளுக்கு',
    'home.vendorDashboard': 'விற்பனையாளர் டாஷ்போர்டு',
    'home.howToJoin': 'எப்படி சேருவது',
    'home.support': 'ஆதரவு',
    'home.helpCenter': 'உதவி மையம்',
    'home.privacy': 'தனியுரிமை',
    'home.connectingStores': 'சிறந்த ஷாப்பிங் அனுபவத்திற்காக உள்ளூர் கடைகளை வாடிக்கையாளர்களுடன் இணைத்தல்.',
    
    // Login/Signup
    'auth.login': 'உள்நுழை',
    'auth.signup': 'பதிவு செய்',
    'auth.email': 'மின்னஞ்சல்',
    'auth.password': 'கடவுச்சொல்',
    'auth.confirmPassword': 'கடவுச்சொல்லை உறுதிப்படுத்து',
    'auth.phone': 'தொலைபேசி எண்',
    'auth.name': 'முழு பெயர்',
    'auth.storeName': 'கடையின் பெயர்',
    'auth.address': 'முகவரி',
    'auth.rememberMe': 'என்னை நினைவில் வைத்துக்கொள்',
    'auth.forgotPassword': 'கடவுச்சொல் மறந்துவிட்டதா?',
    'auth.dontHaveAccount': 'கணக்கு இல்லையா?',
    'auth.alreadyHaveAccount': 'ஏற்கனவே கணக்கு உள்ளதா?',
    'auth.customerLogin': 'வாடிக்கையாளர் உள்நுழைவு',
    'auth.vendorLogin': 'கடை உரிமையாளர் உள்நுழைவு',
    'auth.deliveryLogin': 'டெலிவரி பார்ட்னர் உள்நுழைவு',
    'auth.customerSignup': 'வாடிக்கையாளர் பதிவு',
    'auth.vendorSignup': 'கடை உரிமையாளர் பதிவு',
    'auth.deliverySignup': 'டெலிவரி பார்ட்னர் பதிவு',
  },
  
  kn: {
    // Navigation
    'nav.home': 'ಮುಖಪುಟ',
    'nav.shop': 'ಅಂಗಡಿ',
    'nav.cart': 'ಕಾರ್ಟ್',
    'nav.profile': 'ಪ್ರೊಫೈಲ್',
    'nav.language': 'ಭಾಷೆ',
    
    // Common
    'common.addToCart': 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ',
    'common.quantity': 'ಪ್ರಮಾಣ',
    'common.price': 'ಬೆಲೆ',
    'common.total': 'ಒಟ್ಟು',
    'common.subtotal': 'ಉಪ-ಒಟ್ಟು',
    'common.deliveryFee': 'ವಿತರಣಾ ಶುಲ್ಕ',
    'common.free': 'ಉಚಿತ',
    'common.checkout': 'ಚೆಕ್‌ಔಟ್',
    'common.continue': 'ಮುಂದುವರಿಸಿ',
    'common.cancel': 'ರದ್ದುಗೊಳಿಸಿ',
    'common.save': 'ಉಳಿಸಿ',
    'common.edit': 'ಸಂಪಾದಿಸಿ',
    'common.delete': 'ಅಳಿಸಿ',
    'common.view': 'ನೋಡಿ',
    'common.close': 'ಮುಚ್ಚಿ',
    'common.back': 'ಹಿಂದೆ',
    'common.next': 'ಮುಂದೆ',
    'common.previous': 'ಹಿಂದಿನ',
    'common.search': 'ಹುಡುಕಿ',
    'common.filter': 'ಫಿಲ್ಟರ್',
    'common.sort': 'ವಿಂಗಡಿಸಿ',
    'common.all': 'ಎಲ್ಲಾ',
    'common.yes': 'ಹೌದು',
    'common.no': 'ಇಲ್ಲ',
    'common.ok': 'ಸರಿ',
    
    // Delivery Options
    'delivery.delivery': 'ಮನೆ ವಿತರಣೆ',
    'delivery.walkIn': 'ನಡೆದು ಬಂದು ತೆಗೆದುಕೊಳ್ಳಿ',
    'delivery.scheduled': 'ನಿಗದಿತ ಆದೇಶ',
    'delivery.selectOption': 'ವಿತರಣಾ ಆಯ್ಕೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'delivery.deliveryDesc': 'ನಿಮ್ಮ ಆದೇಶವನ್ನು ಮನೆಗೆ ತಲುಪಿಸಿ',
    'delivery.walkInDesc': 'ಅಂಗಡಿಯಿಂದ ನಿಮ್ಮ ಆದೇಶವನ್ನು ತೆಗೆದುಕೊಳ್ಳಿ',
    'delivery.scheduledDesc': 'ನಂತರ ತೆಗೆದುಕೊಳ್ಳಲು ಅಥವಾ ವಿತರಣೆಗೆ ನಿಮ್ಮ ಆದೇಶವನ್ನು ನಿಗದಿಪಡಿಸಿ',
    'delivery.selectTime': 'ಸಮಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'delivery.selectDate': 'ದಿನಾಂಕವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    
    // Recipe Packages
    'recipe.packages': 'ವ್ಯಂಜನ ಪ್ಯಾಕೇಜ್',
    'recipe.suggested': 'ಸೂಚಿಸಿದ ಭಕ್ಷ್ಯಗಳು',
    'recipe.ingredients': 'ಪದಾರ್ಥಗಳು',
    'recipe.discount': '10% ರಿಯಾಯಿತಿ',
    'recipe.chickenBiryani': 'ಚಿಕನ್ ಬಿರ್ಯಾನಿ',
    'recipe.dalRice': 'ದಾಲ್ ಅನ್ನ',
    'recipe.vegetableCurry': 'ತರಕಾರಿ ಕರಿ',
    'recipe.eggFriedRice': 'ಮೊಟ್ಟೆ ಫ್ರೈಡ್ ರೈಸ್',
    'recipe.paneerButterMasala': 'ಪನೀರ್ ಬಟರ್ ಮಸಾಲಾ',
    'recipe.addPackage': 'ಕಾರ್ಟ್‌ಗೆ ಪ್ಯಾಕೇಜ್ ಸೇರಿಸಿ',
    'recipe.serves': 'ಸೇವೆಗಳು',
    'recipe.persons': 'ಜನರು',
    
    // Categories
    'category.riceGrains': 'ಅಕ್ಕಿ ಮತ್ತು ಧಾನ್ಯಗಳು',
    'category.pulses': 'ಬೇಳೆಗಳು',
    'category.cookingOil': 'ಅಡುಗೆ ಎಣ್ಣೆ',
    'category.dairy': 'ಹಾಲು ಉತ್ಪನ್ನಗಳು',
    'category.vegetables': 'ತರಕಾರಿಗಳು',
    'category.bakery': 'ಬೇಕರಿ',
    'category.spices': 'ಮಸಾಲೆಗಳು',
    'category.beverages': 'ಪಾನೀಯಗಳು',
    'category.snacks': 'ನಾಸ್ತೆ',
    'category.chicken': 'ಚಿಕನ್',
    'category.mutton': 'ಮಟನ್',
    'category.fish': 'ಮೀನು',
    'category.beef': 'ಬೀಫ್',
    'category.pork': 'ಪೋರ್ಕ್',
    'category.personalCare': 'ವೈಯಕ್ತಿಕ ಕಾಳಜಿ',
    'category.household': 'ಮನೆ ಸಾಮಗ್ರಿಗಳು',
    
    // Store Types
    'store.kirana': 'ಕಿರಾಣಾ ಅಂಗಡಿ',
    'store.supermarket': 'ಸೂಪರ್ ಮಾರ್ಕೆಟ್',
    'store.meat': 'ಮಾಂಸ ಅಂಗಡಿ',
    'store.local': 'ಸ್ಥಳೀಯ ಅಂಗಡಿಗಳು',
    'store.nearYou': 'ನಿಮ್ಮ ಹತ್ತಿರ',
    'store.open': 'ಅಂಗಡಿಗಳು ತೆರೆದಿವೆ',
    
    // Popular Products
    'products.popular': 'ಜನಪ್ರಿಯ ಉತ್ಪನ್ನಗಳು',
    'products.featured': 'ವಿಶೇಷ ಉತ್ಪನ್ನಗಳು',
    'products.recommended': 'ನಿಮಗೆ ಶಿಫಾರಸು ಮಾಡಿದವು',
    
    // Checkout
    'checkout.title': 'ಚೆಕ್‌ಔಟ್',
    'checkout.deliveryAddress': 'ವಿತರಣಾ ವಿಳಾಸ',
    'checkout.paymentMethod': 'ಪಾವತಿ ವಿಧಾನ',
    'checkout.orderSummary': 'ಆದೇಶ ಸಾರಾಂಶ',
    'checkout.placeOrder': 'ಆದೇಶ ನೀಡಿ',
    'checkout.processing': 'ಪಾವತಿ ಸಂಸ್ಕರಿಸಲಾಗುತ್ತಿದೆ...',
    'checkout.success': 'ಆದೇಶ ಯಶಸ್ವಿಯಾಗಿ ನೀಡಲಾಗಿದೆ!',
    'checkout.failed': 'ಪಾವತಿ ವಿಫಲ',
    
    // Cart
    'cart.title': 'ಶಾಪಿಂಗ್ ಕಾರ್ಟ್',
    'cart.empty': 'ನಿಮ್ಮ ಕಾರ್ಟ್ ಖಾಲಿಯಾಗಿದೆ',
    'cart.continueShopping': 'ಶಾಪಿಂಗ್ ಮುಂದುವರಿಸಿ',
    'cart.proceedToCheckout': 'ಚೆಕ್‌ಔಟ್‌ಗೆ ಹೋಗಿ',
    'cart.removeItem': 'ಐಟಂ ಅಳಿಸಿ',
    'cart.updateQuantity': 'ಪ್ರಮಾಣವನ್ನು ನವೀಕರಿಸಿ',
    
    // Time
    'time.minutes': 'ನಿಮಿಷಗಳು',
    'time.hours': 'ಗಂಟೆಗಳು',
    'time.days': 'ದಿನಗಳು',
    'time.weeks': 'ವಾರಗಳು',
    'time.months': 'ತಿಂಗಳುಗಳು',
    'time.years': 'ವರ್ಷಗಳು',
    
    // Home Page
    'home.title': 'From Your Street, To Your Seat',
    'home.subtitle': 'Connect with your local stores in Bangalore. Get fresh groceries, daily essentials, and more delivered to your doorstep.',
    'home.startShopping': 'ಶಾಪಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ',
    'home.startShoppingNow': 'ಈಗ ಶಾಪಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ',
    'home.joinAsVendor': 'ಸ್ಟೋರ್ ಮಾಲೀಕರಾಗಿ ಸೇರಿ',
    'home.joinAsDelivery': 'ಡೆಲಿವರಿ ಪಾರ್ಟನರ್ ಆಗಿ ಸೇರಿ',
    'home.whyChoose': 'ಏಕೆ ಕಿರೋವನ್ನು ಆರಿಸಬೇಕು?',
    'home.features': 'ವೈಶಿಷ್ಟ್ಯಗಳು',
    'home.howItWorks': 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    'home.contact': 'ಸಂಪರ್ಕ',
    'home.localStores': 'ಸ್ಥಳೀಯ ಅಂಗಡಿಗಳು',
    'home.happyCustomers': 'ಸಂತೋಷದ ಗ್ರಾಹಕರು',
    'home.avgDelivery': 'ಸರಾಸರಿ ಡೆಲಿವರಿ',
    'home.rating': 'ರೇಟಿಂಗ್',
    'home.product': 'ಉತ್ಪನ್ನ',
    'home.forStoresTitle': 'ಅಂಗಡಿಗಳಿಗೆ',
    'home.vendorDashboard': 'ವೆಂಡರ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'home.howToJoin': 'ಹೇಗೆ ಸೇರುವುದು',
    'home.support': 'ಬೆಂಬಲ',
    'home.helpCenter': 'ಸಹಾಯ ಕೇಂದ್ರ',
    'home.privacy': 'ಗೌಪ್ಯತೆ',
    'home.connectingStores': 'ಉತ್ತಮ ಶಾಪಿಂಗ್ ಅನುಭವಕ್ಕಾಗಿ ಸ್ಥಳೀಯ ಅಂಗಡಿಗಳನ್ನು ಗ್ರಾಹಕರೊಂದಿಗೆ ಸಂಪರ್ಕಿಸುವುದು.',
    
    // Login/Signup
    'auth.login': 'ಲಾಗಿನ್',
    'auth.signup': 'ಸೈನ್ ಅಪ್',
    'auth.email': 'ಇಮೇಲ್',
    'auth.password': 'ಪಾಸ್‌ವರ್ಡ್',
    'auth.confirmPassword': 'ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    'auth.phone': 'ಫೋನ್ ಸಂಖ್ಯೆ',
    'auth.name': 'ಪೂರ್ಣ ಹೆಸರು',
    'auth.storeName': 'ಅಂಗಡಿಯ ಹೆಸರು',
    'auth.address': 'ವಿಳಾಸ',
    'auth.rememberMe': 'ನನ್ನನ್ನು ನೆನಪಿಡಿ',
    'auth.forgotPassword': 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?',
    'auth.dontHaveAccount': 'ಖಾತೆ ಇಲ್ಲವೇ?',
    'auth.alreadyHaveAccount': 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
    'auth.customerLogin': 'ಗ್ರಾಹಕ ಲಾಗಿನ್',
    'auth.vendorLogin': 'ಸ್ಟೋರ್ ಮಾಲೀಕ ಲಾಗಿನ್',
    'auth.deliveryLogin': 'ಡೆಲಿವರಿ ಪಾರ್ಟನರ್ ಲಾಗಿನ್',
    'auth.customerSignup': 'ಗ್ರಾಹಕ ಸೈನ್ ಅಪ್',
    'auth.vendorSignup': 'ಸ್ಟೋರ್ ಮಾಲೀಕ ಸೈನ್ ಅಪ್',
    'auth.deliverySignup': 'ಡೆಲಿವರಿ ಪಾರ್ಟನರ್ ಸೈನ್ ಅಪ್',
  },
  
  ml: {
    // Navigation
    'nav.home': 'ഹോം',
    'nav.shop': 'ഷോപ്പ്',
    'nav.cart': 'കാർട്ട്',
    'nav.profile': 'പ്രൊഫൈൽ',
    'nav.language': 'ഭാഷ',
    
    // Common
    'common.addToCart': 'കാർട്ടിലേക്ക് ചേർക്കുക',
    'common.quantity': 'അളവ്',
    'common.price': 'വില',
    'common.total': 'മൊത്തം',
    'common.subtotal': 'ഉപ-മൊത്തം',
    'common.deliveryFee': 'ഡെലിവറി ഫീസ്',
    'common.free': 'സൗജന്യം',
    'common.checkout': 'ചെക്ക്‌ഔട്ട്',
    'common.continue': 'തുടരുക',
    'common.cancel': 'റദ്ദാക്കുക',
    'common.save': 'സേവ് ചെയ്യുക',
    'common.edit': 'എഡിറ്റ് ചെയ്യുക',
    'common.delete': 'ഇല്ലാതാക്കുക',
    'common.view': 'കാണുക',
    'common.close': 'അടയ്ക്കുക',
    'common.back': 'പിന്നോട്ട്',
    'common.next': 'അടുത്തത്',
    'common.previous': 'മുമ്പത്തെ',
    'common.search': 'തിരയുക',
    'common.filter': 'ഫിൽട്ടർ',
    'common.sort': 'സോർട്ട്',
    'common.all': 'എല്ലാം',
    'common.yes': 'അതെ',
    'common.no': 'ഇല്ല',
    'common.ok': 'ശരി',
    
    // Delivery Options
    'delivery.delivery': 'ഹോം ഡെലിവറി',
    'delivery.walkIn': 'വാക്ക്-ഇൻ പിക്കപ്പ്',
    'delivery.scheduled': 'ഷെഡ്യൂൾ ഓർഡർ',
    'delivery.selectOption': 'ഡെലിവറി ഓപ്ഷൻ തിരഞ്ഞെടുക്കുക',
    'delivery.deliveryDesc': 'നിങ്ങളുടെ ഓർഡർ വീട്ടിലേക്ക് ഡെലിവർ ചെയ്യുക',
    'delivery.walkInDesc': 'സ്റ്റോറിൽ നിന്ന് നിങ്ങളുടെ ഓർഡർ എടുക്കുക',
    'delivery.scheduledDesc': 'പിന്നീട് പിക്കപ്പ് അല്ലെങ്കിൽ ഡെലിവറിക്കായി നിങ്ങളുടെ ഓർഡർ ഷെഡ്യൂൾ ചെയ്യുക',
    'delivery.selectTime': 'സമയം തിരഞ്ഞെടുക്കുക',
    'delivery.selectDate': 'തീയതി തിരഞ്ഞെടുക്കുക',
    
    // Recipe Packages
    'recipe.packages': 'റെസിപ്പി പാക്കേജുകൾ',
    'recipe.suggested': 'സൂചിപ്പിച്ച വിഭവങ്ങൾ',
    'recipe.ingredients': 'ചേരുവകൾ',
    'recipe.discount': '10% കിഴിവ്',
    'recipe.chickenBiryani': 'ചിക്കൻ ബിരിയാണി',
    'recipe.dalRice': 'ദാൽ ചോറ്',
    'recipe.vegetableCurry': 'പച്ചക്കറി കറി',
    'recipe.eggFriedRice': 'മുട്ട ഫ്രൈഡ് റൈസ്',
    'recipe.paneerButterMasala': 'പനീർ ബട്ടർ മസാല',
    'recipe.addPackage': 'കാർട്ടിലേക്ക് പാക്കേജ് ചേർക്കുക',
    'recipe.serves': 'സേവിക്കുന്നു',
    'recipe.persons': 'ആളുകൾ',
    
    // Categories
    'category.riceGrains': 'അരി & ധാന്യങ്ങൾ',
    'category.pulses': 'പയർവർഗ്ഗങ്ങൾ',
    'category.cookingOil': 'പാചക എണ്ണ',
    'category.dairy': 'പാൽ ഉൽപ്പന്നങ്ങൾ',
    'category.vegetables': 'പച്ചക്കറികൾ',
    'category.bakery': 'ബേക്കറി',
    'category.spices': 'സുഗന്ധവ്യഞ്ജനങ്ങൾ',
    'category.beverages': 'പാനീയങ്ങൾ',
    'category.snacks': 'ലഘുഭക്ഷണം',
    'category.chicken': 'ചിക്കൻ',
    'category.mutton': 'മട്ടൻ',
    'category.fish': 'മത്സ്യം',
    'category.beef': 'ബീഫ്',
    'category.pork': 'പോർക്ക്',
    'category.personalCare': 'വ്യക്തിഗത പരിചരണം',
    'category.household': 'വീട്ടുസാമാനങ്ങൾ',
    
    // Store Types
    'store.kirana': 'കിരാണ സ്റ്റോർ',
    'store.supermarket': 'സൂപ്പർമാർക്കറ്റ്',
    'store.meat': 'മാംസ സ്റ്റോർ',
    'store.local': 'പ്രാദേശിക സ്റ്റോറുകൾ',
    'store.nearYou': 'നിങ്ങളുടെ അടുത്ത്',
    'store.open': 'സ്റ്റോറുകൾ തുറന്നിരിക്കുന്നു',
    
    // Popular Products
    'products.popular': 'ജനപ്രിയ ഉൽപ്പന്നങ്ങൾ',
    'products.featured': 'വിശേഷ ഉൽപ്പന്നങ്ങൾ',
    'products.recommended': 'നിങ്ങൾക്ക് ശുപാർശ ചെയ്തവ',
    
    // Checkout
    'checkout.title': 'ചെക്ക്‌ഔട്ട്',
    'checkout.deliveryAddress': 'ഡെലിവറി വിലാസം',
    'checkout.paymentMethod': 'പേയ്‌മെന്റ് രീതി',
    'checkout.orderSummary': 'ഓർഡർ സംഗ്രഹം',
    'checkout.placeOrder': 'ഓർഡർ ചെയ്യുക',
    'checkout.processing': 'പേയ്‌മെന്റ് പ്രോസസ്സിംഗ്...',
    'checkout.success': 'ഓർഡർ വിജയകരമായി വച്ചു!',
    'checkout.failed': 'പേയ്‌മെന്റ് പരാജയം',
    
    // Cart
    'cart.title': 'ഷോപ്പിംഗ് കാർട്ട്',
    'cart.empty': 'നിങ്ങളുടെ കാർട്ട് ശൂന്യമാണ്',
    'cart.continueShopping': 'ഷോപ്പിംഗ് തുടരുക',
    'cart.proceedToCheckout': 'ചെക്ക്‌ഔട്ടിലേക്ക് പോകുക',
    'cart.removeItem': 'ഇനം നീക്കം ചെയ്യുക',
    'cart.updateQuantity': 'അളവ് അപ്ഡേറ്റ് ചെയ്യുക',
    
    // Time
    'time.minutes': 'മിനിറ്റുകൾ',
    'time.hours': 'മണിക്കൂറുകൾ',
    'time.days': 'ദിവസങ്ങൾ',
    'time.weeks': 'ആഴ്ചകൾ',
    'time.months': 'മാസങ്ങൾ',
    'time.years': 'വർഷങ്ങൾ',
    
    // Home Page
    'home.title': 'From Your Street, To Your Seat',
    'home.subtitle': 'Connect with your local stores in Bangalore. Get fresh groceries, daily essentials, and more delivered to your doorstep.',
    'home.startShopping': 'ഷോപ്പിംഗ് ആരംഭിക്കുക',
    'home.startShoppingNow': 'ഇപ്പോൾ ഷോപ്പിംഗ് ആരംഭിക്കുക',
    'home.joinAsVendor': 'സ്റ്റോർ ഉടമയായി ചേരുക',
    'home.joinAsDelivery': 'ഡെലിവറി പാർട്നറായി ചേരുക',
    'home.whyChoose': 'എന്തുകൊണ്ട് കിരോയെ തിരഞ്ഞെടുക്കണം?',
    'home.features': 'സവിശേഷതകൾ',
    'home.howItWorks': 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു',
    'home.contact': 'ബന്ധപ്പെടുക',
    'home.localStores': 'പ്രാദേശിക സ്റ്റോറുകൾ',
    'home.happyCustomers': 'സന്തോഷമുള്ള ഉപഭോക്താക്കൾ',
    'home.avgDelivery': 'ശരാശരി ഡെലിവറി',
    'home.rating': 'റേറ്റിംഗ്',
    'home.product': 'ഉൽപ്പന്നം',
    'home.forStoresTitle': 'സ്റ്റോറുകൾക്ക്',
    'home.vendorDashboard': 'വെൻഡർ ഡാഷ്‌ബോർഡ്',
    'home.howToJoin': 'എങ്ങനെ ചേരാം',
    'home.support': 'പിന്തുണ',
    'home.helpCenter': 'സഹായ കേന്ദ്രം',
    'home.privacy': 'സ്വകാര്യത',
    'home.connectingStores': 'മികച്ച ഷോപ്പിംഗ് അനുഭവത്തിനായി പ്രാദേശിക സ്റ്റോറുകളെ ഉപഭോക്താക്കളുമായി ബന്ധിപ്പിക്കുന്നു.',
    
    // Login/Signup
    'auth.login': 'ലോഗിൻ',
    'auth.signup': 'സൈൻ അപ്പ്',
    'auth.email': 'ഇമെയിൽ',
    'auth.password': 'പാസ്‌വേഡ്',
    'auth.confirmPassword': 'പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
    'auth.phone': 'ഫോൺ നമ്പർ',
    'auth.name': 'പൂർണ്ണ നാമം',
    'auth.storeName': 'സ്റ്റോറിന്റെ പേര്',
    'auth.address': 'വിലാസം',
    'auth.rememberMe': 'എന്നെ ഓർക്കുക',
    'auth.forgotPassword': 'പാസ്‌വേഡ് മറന്നുപോയി?',
    'auth.dontHaveAccount': 'അക്കൗണ്ട് ഇല്ലേ?',
    'auth.alreadyHaveAccount': 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
    'auth.customerLogin': 'ഉപഭോക്താ ലോഗിൻ',
    'auth.vendorLogin': 'സ്റ്റോർ ഉടമ ലോഗിൻ',
    'auth.deliveryLogin': 'ഡെലിവറി പാർട്നർ ലോഗിൻ',
    'auth.customerSignup': 'ഉപഭോക്താ സൈൻ അപ്പ്',
    'auth.vendorSignup': 'സ്റ്റോർ ഉടമ സൈൻ അപ്പ്',
    'auth.deliverySignup': 'ഡെലിവറി പാർട്നർ സൈൻ അപ്പ്',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
